#!/usr/bin/env python3
"""Generate the device-tree overlay for a DSI panel from a .panel definition.

The panel is attached DIRECTLY to the SoC's DSI host - there is no bridge
node. Panels of this family carry a self-configuring DSI-to-RGB bridge (e.g.
Chipone ICN6211) that needs no host programming; Linux just feeds it video.
This mirrors how Raspberry Pi describes the same panels.

Usage: gen-overlay.py <panel.def.sh> <out.dts>
"""
import subprocess
import sys

KEYS = ["PANEL_ID", "PANEL_COMPATIBLE", "PANEL_CTRL_COMPATIBLE",
        "PANEL_CTRL_ADDR", "WIDTH_MM", "HEIGHT_MM", "DSI_LANES",
        "TOUCH_COMPATIBLE", "TOUCH_ADDR", "TOUCH_SIZE_X", "TOUCH_SIZE_Y",
        "TOUCH_INVERT_X", "TOUCH_INVERT_Y", "TOUCH_RESET_GPIO"]


def load_def(path):
    script = ". '%s'; " % path + "; ".join(
        'printf "%%s=%%s\\n" %s "$%s"' % (k, k) for k in KEYS)
    out = subprocess.run(["sh", "-c", script], capture_output=True, text=True,
                         check=True).stdout
    d = {}
    for line in out.splitlines():
        k, _, v = line.partition("=")
        d[k] = v
    return d


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    d = load_def(sys.argv[1])

    lanes = int(d["DSI_LANES"] or 1)
    # msm numbers physical lanes from 0
    lane_list = " ".join(str(i) for i in range(lanes))

    ctrl_addr = d.get("PANEL_CTRL_ADDR", "")
    have_ctrl = bool(ctrl_addr)
    touch_addr = d.get("TOUCH_ADDR", "")
    have_touch = bool(touch_addr) and have_ctrl

    i2c_nodes = ""
    if have_ctrl:
        i2c_nodes += f"""
\t\t\treg_display: regulator@{ctrl_addr.replace('0x', '')} {{
\t\t\t\tcompatible = "{d['PANEL_CTRL_COMPATIBLE']}";
\t\t\t\treg = <{ctrl_addr}>;
\t\t\t\tgpio-controller;
\t\t\t\t#gpio-cells = <2>;
\t\t\t}};
"""
    if have_touch:
        inv = ""
        if d.get("TOUCH_INVERT_X") == "1":
            inv += "\t\t\t\ttouchscreen-inverted-x;\n"
        if d.get("TOUCH_INVERT_Y") == "1":
            inv += "\t\t\t\ttouchscreen-inverted-y;\n"
        rst = ""
        if d.get("TOUCH_RESET_GPIO"):
            rst = (f"\t\t\t\treset-gpio = <&reg_display "
                   f"{d['TOUCH_RESET_GPIO']} 1>;\n")
        i2c_nodes += f"""
\t\t\ttouchscreen@{touch_addr.replace('0x', '')} {{
\t\t\t\tcompatible = "{d['TOUCH_COMPATIBLE']}";
\t\t\t\treg = <{touch_addr}>;
\t\t\t\tvcc-supply = <&reg_display>;
{rst}\t\t\t\ttouchscreen-size-x = <{d['TOUCH_SIZE_X']}>;
\t\t\t\ttouchscreen-size-y = <{d['TOUCH_SIZE_Y']}>;
{inv}\t\t\t}};
"""

    supplies = ""
    if have_ctrl:
        supplies = ("\t\t\t\tpower-supply = <&reg_display>;\n"
                    "\t\t\t\tbacklight = <&reg_display>;\n")

    bridge_reg = ""
    if have_ctrl:
        bridge_reg = """
\t/*
\t * Fixed regulator gated by gpio 0 of the panel controller - the line that
\t * releases the on-panel bridge from reset. Raspberry Pi's overlays for
\t * these panels declare the same thing.
\t */
\tfragment@1 {
\t\ttarget-path = "/";
\t\t__overlay__ {
\t\t\treg_bridge: reg-bridge {
\t\t\t\tcompatible = "regulator-fixed";
\t\t\t\tregulator-name = "bridge_reg";
\t\t\t\tgpio = <&reg_display 0 0>;
\t\t\t\tvin-supply = <&reg_display>;
\t\t\t\tenable-active-high;
\t\t\t\tregulator-always-on;
\t\t\t};
\t\t};
\t};
"""

    dts = f"""// SPDX-License-Identifier: GPL-2.0
/*
 * {d['PANEL_ID']} on Arduino UNO Q + UNO Media Carrier.
 *
 * GENERATED by tools/gen-overlay.py from a .panel definition.
 * Do not edit by hand - edit the .panel file and re-run install.sh.
 *
 * The panel attaches directly to the SoC DSI host. There is deliberately no
 * bridge node: panels of this family carry a self-configuring DSI-to-RGB
 * bridge that requires no host programming.
 */

/dts-v1/;
/plugin/;

/ {{
\t/* panel controller and touch on the carrier's CCI I2C bus */
\tfragment@0 {{
\t\ttarget = <&cci_i2c0>;
\t\t__overlay__ {{
\t\t\t#address-cells = <1>;
\t\t\t#size-cells = <0>;
{i2c_nodes}\t\t}};
\t}};
{bridge_reg}
\t/* the panel, attached directly to the DSI host */
\tfragment@2 {{
\t\ttarget = <&mdss_dsi0>;
\t\t__overlay__ {{
\t\t\t#address-cells = <1>;
\t\t\t#size-cells = <0>;
\t\t\tvdda-supply = <&pm4125_l5>;
\t\t\tstatus = "okay";

\t\t\tpanel: panel@0 {{
\t\t\t\tcompatible = "{d['PANEL_COMPATIBLE']}";
\t\t\t\treg = <0>;
{supplies}
\t\t\t\tport {{
\t\t\t\t\tpanel_in: endpoint {{
\t\t\t\t\t\tremote-endpoint = <&mdss_dsi0_out>;
\t\t\t\t\t}};
\t\t\t\t}};
\t\t\t}};
\t\t}};
\t}};

\t/* DSI host output -> panel */
\tfragment@3 {{
\t\ttarget = <&mdss_dsi0_out>;
\t\t__overlay__ {{
\t\t\tremote-endpoint = <&panel_in>;
\t\t\tdata-lanes = <{lane_list}>;
\t\t}};
\t}};
}};
"""
    open(sys.argv[2], "w").write(dts)
    print("  wrote %s (%d DSI lane%s)"
          % (sys.argv[2], lanes, "" if lanes == 1 else "s"))


if __name__ == "__main__":
    main()
