#!/usr/bin/env python3
"""Assemble a .panel file from facts the wizard has gathered.

    write-panel.py --id waveshare-3in4-touch-c \
                   --desc "Waveshare 3.4inch DSI-TOUCH-C (800x800)" \
                   --mode 800x800 \
                   --compatible waveshare,3.4-dsi-touch-c \
                   --lanes 2 --clock 44300 \
                   --fingerprint submissions/<id>/fingerprint.txt \
                   --out panels/waveshare-3in4-touch-c.panel

Written in Python rather than assembled with sed because a .panel file is
mostly prose, and the prose is the point: every definition here explains what
was measured, what was assumed, and what is still unverified. Generating one
without those notes would produce a file that looks as authoritative as the
hand-written ones while standing on far less.

So the generated file says, in its own words, that it was generated - and
carries the specific things a reviewer should not take on trust.
"""
import argparse
import io
import re
import sys


HEADER = '''# {desc}
#
# GENERATED by tools/new-panel.sh on a board with this panel attached.
# Everything below marked MEASURED came off the hardware. Everything marked
# ASSUMED did not - read those before trusting this file, and delete this
# notice once you have.
#
# A derived panel: the UNO Q kernel has no mode for it and Arduino ships no
# overlay, but Raspberry Pi's tree carries the mode, the DSI parameters and
# the vendor initialisation sequence. scripts/16-install-derived-panel.sh
# fetches that driver, trims it to this panel alone, builds it, and derives an
# overlay from Arduino's 10.1 inch one.
#
# MEASURED on this panel:
#
{measured}#
# ASSUMED, because nothing on the panel reports them - they come from the
# upstream driver entry named below:
#
#     mode          {mode}
#     DSI lanes     {lanes}
#     pixel clock   {clock}
#     init sequence  the vendor sequence in that driver
#
# A DSI panel carries no EDID, so none of that is readable from the hardware.
# If the picture is wrong but present, the upstream entry is the thing to
# doubt first - see tools/match-upstream.py, which lists the alternatives at
# this resolution.

PANEL_ID="{pid}"
PANEL_DESC="{desc}"

DERIVED_PANEL=1
STOCK_MODE="{mode}"

# --- the driver ------------------------------------------------------------
DRIVER_URL="https://raw.githubusercontent.com/raspberrypi/linux/rpi-6.12.y/drivers/gpu/drm/panel/panel-waveshare-dsi-v2.c"
DRIVER_PATCHER="tools/patch-waveshare-panel.py"

# The patcher finds this entry in the driver's match table and keeps only the
# descriptor, mode and initialisation sequence it points at.
PANEL_DT_COMPATIBLE="{compatible}"

# --- the overlay -----------------------------------------------------------
# Arduino's 10.1 inch overlay describes this carrier correctly; only the panel
# node changes. Installed into the 5 inch slot because arduino-linux-config
# hardcodes its display options and cannot register a new one.
OVERLAY_TEMPLATE_OPTION="10-dsi-touch-a"
CARRIER_DISPLAY_OPTION="5-dsi-touch-a"

# GPIO lines on the panel's own controller at 0x45. ASSUMED: these are the
# values every derived panel here uses - the line numbers are Arduino's and the
# polarity is Raspberry Pi's, because that driver sequences these itself. If
# the backlight comes on but the screen stays dark with a clean dmesg, this is
# the first place to look.
RESET_GPIO_LINE=1
IOVCC_GPIO_LINE=4
AVDD_GPIO_LINE=0

# --- touch -----------------------------------------------------------------
# ASSUMED: no transform. {touchnote}
TOUCH_ADDR="0x5d"
TOUCH_SWAP_XY=0
TOUCH_INVERT_X=0
TOUCH_INVERT_Y=0

# goodix_ts also needs its reads split for the CCI bus, which refuses anything
# over 12 bytes - scripts/17-install-goodix-fix.sh, run automatically.
STOCK_DRIVERS="goodix_ts"

# The same hardware upstream, for tools/match-upstream.py.
UPSTREAM_COMPATIBLE="{compatible}"

# --- how detect-panel.sh recognises it -------------------------------------
# MEASURED. Proposed by tools/check-fingerprints.py by comparing this panel
# against every panel recorded in this repository, and choosing the shortest
# chain of reads that separates it from all of them.
DETECT_ADDR="0x5d"
DETECT_NOTE="{note}"

{detect}'''


def fingerprint_lines(path):
    """The DETECT_ lines the suggester proposed, verbatim."""
    out = []
    for line in io.open(path, encoding="utf-8", errors="replace"):
        if re.match(r"^DETECT\d*_(WRITE|READ|EXPECT)=", line.strip()):
            out.append(line.rstrip("\n"))
    return out


def main(argv):
    ap = argparse.ArgumentParser()
    for f in ("id", "desc", "mode", "compatible", "out", "fingerprint"):
        ap.add_argument("--" + f, required=True)
    ap.add_argument("--lanes", default="?")
    ap.add_argument("--clock", default="?")
    ap.add_argument("--measured", default="",
                    help="lines for the MEASURED block, newline separated")
    a = ap.parse_args(argv)

    detect = fingerprint_lines(a.fingerprint)
    if not detect:
        sys.exit("no DETECT_ lines in %s - the fingerprint step did not "
                 "produce a chain, so there is nothing to recognise this "
                 "panel by." % a.fingerprint)

    measured = "".join("#     %s\n" % l for l in a.measured.split("\n") if l)

    w, h = (a.mode.split("x") + ["?"])[:2]
    square = w == h
    touchnote = (
        "The panel is square, so the axes cannot be\n"
        "# told apart by their reported extents - only pointing at a known\n"
        "# corner will settle it. UNVERIFIED until someone does."
        if square else
        "The digitizer's reported extents match the\n"
        "# framebuffer, so the axes should already agree. Worth a finger\n"
        "# before trusting it.")

    clock = ("%.1f MHz" % (int(a.clock) / 1000.0)) if a.clock.isdigit() else a.clock

    body = HEADER.format(
        pid=a.id, desc=a.desc, mode=a.mode, compatible=a.compatible,
        lanes=a.lanes, clock=clock, measured=measured, touchnote=touchnote,
        note="%s - proposed by new-panel.sh, confirmed on hardware" % a.desc,
        detect="\n".join(detect) + "\n")

    io.open(a.out, "w", encoding="utf-8", newline="\n").write(body)
    print("wrote %s" % a.out)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
